const productsArray = [
    {
        id: 1,
        name: 'iPhone X',
        description: 'This is iPhone XS',
        type: 'phone',
        capacity: 64,
        price: 500,
        image: '/images/11promax.png',
    },
    {
        id: 2,
        name: 'iPhone 12',
        description: 'This is iPhone 12',
        type: 'phone',
        capacity: 64,
        price: 750,
        image: '/images/12pro.png',
    },
    {
        id: 3,
        name: 'iPhone 11 Pro Max',
        description: 'This is iPhone 11 Pro Max',
        type: 'phone',
        capacity: 64,
        price: 600,
        image: '/images/11promax.png',
    },
    {
        id: 4,
        name: 'iPhone 13',
        description: 'This is iPhone 13',
        type: 'phone',
        capacity: 64,
        price: 1000,
        image: '/images/13.png',
    },
    {
        id: 5,
        name: 'iPhone 12 Pro',
        description: 'This is iPhone 12 Pro',
        type: 'phone',
        capacity: 64,
        price: 800,
        image: '/images/12pro.png',
    },
    {
        id: 6,
        name: 'iPhone 13 Pro',
        description: 'This is iPhone 13 Pro',
        type: 'phone',
        capacity: 64,
        price: 700,
        image: '/images/iphone13pro.jpeg',
    },
]
export default productsArray
