const productsArray = [
    {
        id: 1,
        name: 'iPhone X',
        description: 'This is iPhone XS',
        type: 'phone',
        capacity: 64,
        price: 500,
    },
    {
        id: 2,
        name: 'iPhone 12',
        description: 'This is iPhone 12',
        type: 'phone',
        capacity: 64,
        price: 750,
    },
    {
        id: 3,
        name: 'iPhone 11 Pro Max',
        description: 'This is iPhone 11 Pro Max',
        type: 'phone',
        capacity: 64,
        price: 600,
    },
    {
        id: 4,
        name: 'iPhone 13',
        description: 'This is iPhone 13',
        type: 'phone',
        capacity: 64,
        price: 1000,
    },
    {
        id: 5,
        name: 'iPhone 12 Pro',
        description: 'This is iPhone 12 Pro',
        type: 'phone',
        capacity: 64,
        price: 800,
    },
    {
        id: 6,
        name: 'iPhone 11',
        description: 'This is iPhone 11',
        type: 'phone',
        capacity: 64,
        price: 700,
    },
]
export default productsArray
